<a href="https://colab.research.google.com/github/GuhNasc/Data-Science/blob/main/PROJETOS_Limpeza_Dataset_com_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introdução do projeto**

Nesse projeto iremos fazer uma limpeza num dataset utilizando `NUMPY` fazendo alterações em alguns dados sem perder a informação que é o mais importante. O conjunto de dados que utilizaremos representa milhares de empréstimos feitos  por meio da plataforma Lending Club, que é uma plataforma que permite que  indivíduos emprestem para outros indivíduos.

Esse conjunto de dados contém dados com muitas strings, caracteres especiais, problemas de encoding, datas  mal  formatadas,  números  e  textos  na  mesma  coluna, url’s contendo Ids importantes para análise, valores ausentes, coluna que contém informação que deveria estar distribuída em três ou mais colunas.

Então faremos todos esse tratamento e limpeza dos dados. 





## **Carregando os dados**

**Importando a biblioteca e importando os dados**

In [1]:
# Importação de bibliotecas
import numpy as np
import pandas as pd
np.set_printoptions(suppress = True, linewidth = 200, precision = 2)

In [2]:
# Carregando os dados e definindo alguns parametros
dados = np.genfromtxt('/content/dataset1.csv', #------Carrega os dados da fonte
                      delimiter = ';',#------ Separa das colunas por ;
                      skip_header = 1,#------ Pula a linha do cabeçalho para carregar somente os dados
                      autostrip = True,#----- Remove espaços dentro de cada coluna 
                      encoding = 'cp1252')

In [3]:
# Verificando o tipo 
type(dados)

numpy.ndarray

In [4]:
# Verficando o tamanho do dataset em LINHAS E COLUNAS , então temos 10000 linhas e 14 colunas
dados.shape

(10000, 14)

In [5]:
# Carregando os dados em visualização+
dados.view()

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

**Podemos ver que há várias colunas com `nan` isso se deve porque tem caracteres especiais e como o numpy carrega dados em formato string, vamos ver quantos casos há nesse dadaset**


## **Verificando Valores Ausentes**

In [6]:
# Somando todos os dados com valores NaN
np.isnan(dados).sum()

88005

Agora vamos utilizar por enquanto um valor coringa para substituir o valor NaN

In [7]:
#Criando variavel coringa
valor_coringa = np.nanmax(dados) + 1
print(valor_coringa)

68616520.0


Geramos esse valor coringa mas ainda irei fazer mais uma alteração no nossos dados separando colunas Strings de colunas Numericas

In [8]:
# Calculando média das colunas numericas ignorando o valor NaN
media_ignorando_nan =  np.nanmean(dados, axis = 0)#-------Com isso vamos trazer as médicas das colunas numéricas , logo tudo aquilo que é NAN é coluna string
print(media_ignorando_nan)

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]


<ipython-input-8-9a951fa80732>:2: RuntimeWarning: Mean of empty slice
  media_ignorando_nan =  np.nanmean(dados, axis = 0)#-------Com isso vamos trazer as médicas das colunas numéricas , logo tudo aquilo que é NAN é coluna string


## **Separando colunas Strings e Numericas**

In [104]:
colunas_strings =  np.argwhere(np.isnan(media_ignorando_nan)).squeeze()# Trazendo colunas strings 
print(colunas_string)

[ 1  3  5  8  9 10 11 12]


In [105]:
colunas_numericas =  np.argwhere(np.isnan(media_ignorando_nan) == False).squeeze()# Trazendo colunas numericas
print(colunas_numericas)

[ 0  2  4  6  7 13]


## **Criando um array com as colunas Strings e Numericas**

In [11]:
# Carrega colunas do tipo string
arr_strings = np.genfromtxt('/content/dataset1.csv',
                            delimiter = ';',
                            skip_header = 1,
                            autostrip = True,
                            usecols = colunas_string,
                            dtype = str,
                            encoding = 'cp1252')

In [12]:
arr_numerica =  np.genfromtxt('/content/dataset1.csv',
                              delimiter = ';',
                              autostrip = True,
                              skip_header = 1,
                              usecols = colunas_numericas,
                              filling_values = valor_coringa,
                              encoding = 'cp1252')

In [13]:
arr_numerica

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [14]:
arr_strings

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

Criando array somente com os nomes da colunas

In [15]:
arr_nomes_colunas = np.genfromtxt('/content/dataset1.csv',
                              delimiter = ';',
                              autostrip = True,
                              skip_footer = dados.shape[0],
                              dtype = str,
                              encoding = 'cp1252')

In [16]:
arr_nomes_colunas

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [110]:
# Separa cabeçalho de colunas numéricas e string
header_strings, header_numerica = arr_nomes_colunas[colunas_string], arr_nomes_colunas[colunas_numericas]

In [111]:
header_strings

array(['issue_d', 'term_months', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [112]:
header_numerica

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

Agora vamos tratar as colunas de strings primeiro.

## **MANIPULANDO VARIÁVEIS STRINGS**

### **Pré-Processamento da Variavel issue_date com Label enconding**

In [17]:
#Extrai os valores unicos da variavel
np.unique(arr_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [18]:
# Removendo o '-15'
arr_strings[:,0] = np.chararray.strip(arr_strings[:,0],'-15')

In [19]:
#Agora vamos extrair novamente os valores unicos
np.unique(arr_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

Percebemos que na primeira posição tem um valor ausente. Primeiramente iremos fazer uma alteração nos dados transformando os nomes dos meses em numeros , então Jan = 1 , Feb = 2 e no valor ausente iremos utilizar o numero 0

In [20]:
# Criando um array de meses incluindo o valor ausente que está na primeira posição
meses = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [21]:
#Loop para converter os meses em numericos
for i in range(13):
  arr_strings[:,0] = np.where(arr_strings[:,0] == meses[i],i,arr_strings[:,0])

In [22]:
np.unique(arr_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

Temos a primeira váriavel categórica sendo convertida para numerica. Agora irei fazer o mesmo com a variavel Loan_status

### **Pré-Processamento da variavel Loan_Status com binarização**

In [23]:
#Extraindo os valores unicos dessa variavel
np.unique(arr_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [24]:
#Numero de elementos que podem ser utilizados
np.unique(arr_strings[:,1]).size

9

In [25]:
# Criando um array com somente 3 valores 
status_ruim = np.array(['','Charged Off','Default','Late (31-120days)'])

In [26]:
# Checamos os valores da variavel e comparamos com o array que criamos convertendo somente em 0 e 1
arr_strings[:,1] = np.where(np.isin(arr_strings[:,1],status_ruim),0,1)

In [27]:
# Extraindo os valores binarizados
np.unique(arr_strings[:,1])

array(['0', '1'], dtype='<U69')

### **Pré-Processamento da variavel term utilizando limpeza de string**

In [28]:
#Extraindo os valores unicos da variavel
np.unique(arr_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

Nesse caso, irei remover o `months` no dado e alterar o nome da Variável para `term_months`para nao perder a informação e assim alterar a variável para numerica

In [29]:
# Removendo o months do dado
arr_strings[:,2] = np.chararray.strip(arr_strings[:,2],' months')
arr_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [30]:
# Mudando o nome da variavel para nao perder a informação
arr_nomes_colunas[3] = 'term_months'

Como temos valores ausentes irei mudar para 60 meses

In [31]:
#mudando para valores ausentes para 60
arr_strings[:,2] = np.where(arr_strings[:,2] == '',60, arr_strings[:,2])

In [32]:
# Trazendo valores unicos atualizados
np.unique(arr_strings[:,2])

array(['36', '60'], dtype='<U69')

### Pré-Processamento das variáveis Grade e Sub_Grade com dicionário

In [33]:
# Iremos reformular a variavel subgrade juntando informações da variavel grade
print(arr_nomes_colunas[9])
print(arr_nomes_colunas[8])

sub_grade
grade


In [34]:
# Extraindo valores da sub_grade
np.unique(arr_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
       'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [35]:
# Variável grade
np.unique(arr_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

Como a variável subgrade tem mais informação, juntar as informações da variável grade na Subgrade

In [36]:
# Retirando o valor ausente
np.unique(arr_strings[:,3])[1:,]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [37]:
# Loop para ajuste da variavel subgrade
for i in np.unique(arr_strings[:,3])[1:,]:
  arr_strings[:,4] = np.where ((arr_strings[:,4] == '') & (arr_strings[:,3] == i), i + '5', arr_strings[:,4]) 

In [38]:
# Retornando categorias e suas respectivas contagens
np.unique(arr_strings[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
        'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

 Podemos ver que ainda temos um valor ausente , porém agora iremos trata-lo substituindo pelo valor `H1`

In [39]:
# Substituindo o valor ausente
arr_strings[:,4] = np.where(arr_strings[:,4] == '', 'H1' , arr_strings[:,4])

In [40]:
# Verficando a variavel novamente 
np.unique(arr_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

Pronto agora não temos valor ausente. Agora iremos remover a variável Grade do nosso conjunto de dados. Irei fazer isso pois já juntei as informações na variável subgrade , sendo assim, não faz sentindo ter a variável grade

In [41]:
# Verificando nosso array de strings. Podemos ver que ainda temos que retira a coluna 3 
np.unique(arr_strings[:1])

array(['1', '36', '5', 'C', 'C3', 'CA', 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226'], dtype='<U69')

In [42]:
# Retirando a coluna 3
arr_strings = np.delete(arr_strings,3 ,axis = 1)

In [43]:
# Variavel 3 removida 
np.unique(arr_strings[:1])

array(['1', '36', '5', 'C3', 'CA', 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226'], dtype='<U69')

Agora iremos converter a variável SUB_GRADE para conversão numérica

In [44]:
# Variável subgrade
np.unique(arr_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

Para terminar o tratamento dessa váriavel irei criar um dicionário para que  cada dado tenha uma chave unica 

In [45]:
# Criando as chaves
chave = list(np.unique(arr_strings[:,3]))
chave[0]

'A1'

In [46]:
# Criando uma lista de valores para cada chave
valores = list(range(1, np.unique(arr_strings[:,3]).shape[0] + 1))
valores[0]

1

Com chaves e valores criados , agora irei criar o dicionario utilizando a função `dict` com as variáveis que acabamos de criar 

In [47]:
# Criando o dicionário
dict_sub_grade = dict(zip(chave,valores))

In [48]:
# Visualizando o dicionario
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

Agora iremos substituir os valores da variável sub_grade pelo dicionário

In [49]:
# Loop para substituir os valores da variável sub_grade pelo dicionario
for i in np.unique(arr_strings[:,3]):
  arr_strings[:,3] = np.where(arr_strings[:,3] == i, dict_sub_grade[i], arr_strings[:,3])

In [50]:
# Verificando os valores novos
np.unique(arr_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6',
       '7', '8', '9'], dtype='<U69')

Pronto , agora iremos tratar a proxima variável strings no nosso conjunto de dados

### Pré-Processamento da variável Verification Status com binarização

In [51]:
# Valores unicos da variável
np.unique(arr_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

Temos 3 categorias e um valor ausente. A categoria `source verified` e `verified` são praticamente iguais , então irei juntar as duas. Por fim iremos tratar o valor ausente colocando o valor `NOT VERIFIED`

In [52]:
# Usando binariação
arr_strings[:,4] = np.where((arr_strings[:,4] == '') | (arr_strings[:,4] == 'Not Verified'), 0,1)

In [53]:
# Extraindo os novos valores da variável
np.unique(arr_strings[:,4])

array(['0', '1'], dtype='<U69')

Basicamente utilizei a função **np.where** para fazer 2 validações. 

1 - Verificar se o valor é ausente e se for ausente vai colocar o `0` | 
2 - Verificar se o valor é Not Verified e se for também colocar o `0`

E por fim caso o dado não tivesse submetido nessas condições será colocado o valor `1`

### Pré-Processamento da variável url com extração do ID

In [54]:
# Extraindo valores unicos da variável
arr_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ..., 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

É possível ver que os links são iguais porém há um `ID` que iremos extrair

In [55]:
# Extraindo somente o ID
np.chararray.strip(arr_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [56]:
# Substituindo o dado na coluna inserindo somente os ID's
arr_strings[:,5] = np.chararray.strip(arr_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [57]:
# Verificando os valores substituidos pelo ID
np.unique(arr_strings[:,5])

array(['12606806', '13026045', '1312426', ..., '8138291', '8214572', '849994'], dtype='<U69')

Como essa variável é uma string ainda irei muda-la para numérica

In [58]:
# Convertendo a variável para numérica
arr_strings[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

Investigando os dados é possível concluir que esse `ID` que acabamos de extrair é o mesmo da coluna ID que temos no nosso array de variáveis numéricas.

In [59]:
arr_nomes_colunas[0]

'id'

In [60]:
# Comparando as colunas para saber se tem a mesma informação
np.array_equal(arr_numerica[:,0].astype(dtype = np.int32), arr_strings[:,5].astype(dtype = np.int32))

True

Removendo a coluna ID que extraimos do array de strings para não duplicar informação

In [61]:
# Excluindo coluna ID 
arr_strings = np.delete(arr_strings, 5, axis = 1)

### Pré-Processamento da variável adress com Categorização

In [62]:
# Extrair os valore unicos da variável
np.unique(arr_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [63]:
# Extraindo os nomes e contagem
states_name,  states_count = np.unique(arr_strings[:,5], return_counts = True)

In [64]:
# Ordenando em ordem descrescente
states_count_sorted = np.argsort(-states_count)

In [65]:
# Mostrando o resultado
states_name[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK',
        'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,
          74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10]))

In [66]:
# Substituindo o valor ausente por 0 
arr_strings[:,5] = np.where(arr_strings[:,5] =='',0 ,arr_strings[:,5])

Agora irei separar os estados por regiões de acordo com esse mapa: https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [67]:
# Separando os estados por regioes
state_west = np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
state_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
state_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
state_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI','state'])

In [68]:
# Substituindo o valor do estado pelo numero
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5],state_west),1 , arr_strings[:,5])
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5],state_south),2 , arr_strings[:,5])
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5],state_midwest),3 , arr_strings[:,5])
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5],state_east),4 , arr_strings[:,5])

In [69]:
# Verificando os valores novos
np.unique(arr_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [70]:
# Convertendo o array para numerico
arr_strings = arr_strings.astype(int)

In [71]:
# Verificando o tipo do array
arr_strings.dtype

dtype('int64')

## MANIPULANDO VARIÁVEIS NUMÉRICAS

Verificando o array numerico

In [72]:
# Verificando os valroes
arr_numerica

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

No começo do projeto foi inserido um valor coringa em valores ausentes , logo não temos valores ausentes nesse conjunto 

In [73]:
# Verificando se há valores ausentes
np.isnan(arr_numerica).sum()

0

Criando um array com valor minimo , média e maximo ignorando NAN

In [74]:
# Usando esse array para tratar valores ausentes
arr_stats = np.array([np.nanmin(dados, axis = 0), media_ignorando_nan, np.nanmax(dados, axis= 0)])
print(arr_stats)

[[  373332.           nan     1000.           nan     1000.           nan        6.         31.42         nan         nan         nan         nan         nan        0.  ]
 [54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]
 [68616519.           nan    35000.           nan    35000.           nan       28.99     1372.97         nan         nan         nan         nan         nan    41913.62]]


<ipython-input-74-3a328caf35ab>:2: RuntimeWarning: All-NaN slice encountered
  arr_stats = np.array([np.nanmin(dados, axis = 0), media_ignorando_nan, np.nanmax(dados, axis= 0)])


In [75]:
arr_stats[:, colunas_numericas]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

### Pré-Processamento da variável funded_amnt

In [76]:
# Extraindo os valores da variável
arr_numerica[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [77]:
# Verificando o valor para ser aplicado
arr_stats[0,colunas_numericas[2]]

1000.0

In [78]:
# Ajustando os valores na coluna

arr_numerica[:,2] = np.where(arr_numerica[:,2] == valor_coringa, arr_stats[0, colunas_numericas[2]], arr_numerica[:,2])

In [79]:
arr_numerica[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### Pré-Processamento das variáveis loan_amnt, int_rate, installment e total_pymnt

In [80]:
# Loop para substituir o valor ausente (valor_coringa) pelos valores do array de estatistica
for i in [1,3,4,5]:
  arr_numerica[:,i] = np.where(arr_numerica[:,i] == valor_coringa,
                               arr_stats[2, colunas_numericas[i]],
                               arr_numerica[:,i]
                               )

In [81]:
arr_numerica

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Trabalahando com o segundo dataset

In [83]:
# Carrega o segundo dataset
dados_cot = np.genfromtxt("dataset2.csv", 
                          delimiter = ',', 
                          autostrip = True, 
                          skip_header = 1, 
                          usecols = 3)

In [84]:
# Visualizando os dados
dados_cot

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [88]:
# Verificando o nome das colunas
arr_nomes_colunas

array(['id', 'issue_d', 'loan_amnt', 'term_months', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

Podemos verificar que a coluna issue_d que é nossa coluna de Mês está na posição 1 , logo iremos trabalhar com ela

In [89]:
# A coluna 0 do array de strings é o mês
arr_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [90]:
# Vamos atribuir a coluna de mês à variável chamada exchange_rate
exchange_rate = arr_strings[:,0]

In [91]:
# Verificando se foi atribuido os valroes 
exchange_rate

array([ 5,  0,  9, ...,  6,  4, 12])

In [92]:
# Loop para preencher a variável exchange_rate com a taxa correspondente ao mês
# Usamos dados_cot[i - 1] devido a forma como carregamos os meses para comportar o zero
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i, dados_cot[i - 1], exchange_rate) 

In [93]:
# Verificando os valores depois o loop
exchange_rate

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

In [94]:
# Onde a taxa de câmbio estiver com zero substituímos pela média
exchange_rate = np.where(exchange_rate == 0, np.mean(dados_cot), exchange_rate)

In [95]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

Agora irei verificar se o `exchange_rate` tem o mesmo tamanho que o `array_numerica`

In [96]:
# Tamanho do exchange_rate
exchange_rate.shape

(10000,)

In [98]:
# Tamanho do array numerico
arr_numerica.shape

(10000, 6)

In [99]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [102]:
# Concatenação dos arrays
arr_numerica = np.hstack((arr_numerica, exchange_rate))

In [117]:
# Inclui o nome da coluna no array de nomes de colunas
header_numerica = np.concatenate((header_numerica, np.array(['exchange_rate'])))

In [118]:
header_numerica

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

Agora irei criar colunas para as taxas de câmbio em Dólar e Euro

In [120]:
# Colunas em USD
colunas_dolar = np.array([1,2,4,5])

In [122]:
# Visualiza
arr_numerica[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [123]:
# Tamanho
arr_numerica.shape

(10000, 7)

In [124]:
# Loop pelas colunas em dolar para aplicar a taxa de conversão para EURO
for i in colunas_dolar:
    arr_numerica = np.hstack((arr_numerica, np.reshape(arr_numerica[:,i] / arr_numerica[:,6], (10000,1))))

In [125]:
# Novo tamanho do array
arr_numerica.shape

(10000, 11)

In [127]:
# Visualiza os dados
arr_numerica

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

Vamos aumentar o numero do cabeçalho com colunas novas

In [129]:
header_additional = np.array([arr_nomes_colunas + '_EUR' for arr_nomes_colunas in header_numerica[colunas_dolar]])

In [130]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [131]:
header_numerica = np.concatenate((header_numerica, header_additional))

In [133]:
header_numerica

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [135]:
header_numerica[colunas_dolar] = np.array([arr_nomes_colunas + '_USD' for arr_nomes_colunas in header_numerica[colunas_dolar]])

In [136]:
header_numerica

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [137]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [138]:
header_numerica = header_numerica[columns_index_order]

In [139]:
arr_numerica

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [140]:
arr_numerica = arr_numerica[:,columns_index_order]

### Pré-Processamento da variável int_rate

In [142]:
# Verificando as colunas numericas
header_numerica

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [144]:
# Extraindo os valores
arr_numerica[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [146]:
# Vamos apenas dividir por 100
arr_numerica[:,5] = arr_numerica[:,5] / 100

In [147]:
# Extaindo os valores novos
arr_numerica[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

Pronto , agora para verificar se todos os valores foram preenchidos e que não há nenhum valor ausente irei fazer uma última verificação

In [154]:
# Verifica se tem valor ausente
print(np.isnan(arr_numerica).sum())
print(np.isnan(arr_strings).sum())

0
0


# Conclusão

Foi feita a limpeza dos dados utilizando apenas a biblioteca numpy e alguns conceitos de lógicas de programação. o Array de strings teve um trabalho maior devido todo o processamento com `Label encoding, Binaziração,Categorização e limpeza de strings`.